FROM httpd:2.4

ENV HTTP_DIR /usr/local/apache2/htdocs/cloudera-repo

RUN set -ex; \
  apt update; \
  apt install -y --no-install-recommends wget; \
  rm -rf /var/lib/apt/lists/*; \
  mkdir -p $$HTTP_DIR; \
  wget --no-check-certificate --recursive --no-parent --no-host-directories https://archive.cloudera.com/$type/$version/$os/ -P $$HTTP_DIR
